Creating test database for alias 'default'...
E.
======================================================================
ERROR: test_user_authenticated (gestione_palestra.tests.GetReviewsTestCase.test_user_authenticated)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alefranco41/Tecnologie_Web/techweb/Gestione-Palestra/gestione_palestra/gestione_palestra/tests.py", line 281, in test_user_authenticated
    follow_response = self.client.get(response.url)
                                      ^^^^^^^^^^^^
AttributeError: 'HttpResponse' object has no attribute 'url'

----------------------------------------------------------------------
Ran 2 tests in 0.117s

FAILED (errors=1)
Destroying test database for alias 'default'...
